[package]
name = "embree-sys"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
bindgen = "*"
reqwest = {version = "*",features=["blocking"]}
zip = "0.5"
